### ISSUE TITLE
KapChat doesn't works

### ISSUE THREAD

**Issue by Leeo97one** [bazukas/obs-qtwebkit#26]
I want to show the Twitch chat on my OBS Studio scene via obs-qtwebkit but this URL doesn't render at all: https://www.nightdev.com/hosted/obschat/?channel=leeo97onemc&fade=60&bot_activity=true&prevent_clipping=false
Even without any option: https://www.nightdev.com/hosted/obschat/?channel=leeo97onemc

**Comment by baskervald** [comment]
I'm also having this problem. Not sure what would be causing it.

**Comment by baskervald** [comment]
I've written some CSS for just http://twitch.tv/username/chat if anyone trying to use KapChat wants it:

```css
.chat-header {
  display: none !important;
}

.chat-room {
  top: 0 !important;
}

.chat-interface {
  display: none !important;
}

.chat-messages .tse-scroll-content {
  height: 100% !important;
  width: 100% !important;
}

.ember-chat .chat-messages .chat-line {
  padding: .4rem 2rem !important;
}

.ember-chat .chat-messages {
  bottom: 0 !important;
}

.chat-lines {
  padding: 0px !important;
  margin: 5px !important;
}

*:not(.message-line) {
  background: none !important;
  background-color: none !important;
}

.message-line {
  background: rgba(255,255,255,0.7);
  border-radius: 15px;
  margin-top: 3px !important;
  margin-bottom: 3px !important;
}
```
